# yaml-language-server: $schema=https://json.schemastore.org/prometheus.json

global:
  evaluation_interval: 15s
  scrape_interval: 15s

rule_files:
  - "rules/*.yaml"


scrape_configs:
- honor_labels: true
  job_name: prometheus
  static_configs:
  - labels:
      host: neem
    targets:
    - prometheus:9090

- honor_labels: true
  job_name: node_exporter
  static_configs:
  - labels:
      host: neem
    targets:
    - node_exporter:9100
  - labels:
      host: turris
    targets:
    - 192.168.0.1:9100
  - labels:
      host: baobab
    targets:
    - baobab.lan:9100

- honor_labels: true
  job_name: grafana
  static_configs:
  - labels:
      host: neem
    targets:
    - grafana:3000

- honor_labels: true
  job_name: podman
  static_configs:
  - labels:
      host: neem
    targets:
    - podman_exporter:9882

- honor_labels: true
  job_name: homeassistant
  static_configs:
  - labels:
      __metrics_path__: /api/prometheus
      host: neem
    targets:
    - host.containers.internal:8123

- honor_labels: true
  job_name: wud
  static_configs:
  - labels:
      host: neem
    targets:
    - wud:3000

- honor_labels: true
  job_name: snmp
  static_configs:
  - labels:
      host: baobab
    targets:
    - baobab.lan
  metrics_path: /snmp
  params:
    module:
    - synology
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - source_labels: [__param_target]
      regex: (.*)
      replacement: ${1}:9116
      target_label: __address__
