{
 "title": "Synology NAS",
 "description": "The Synology NAS Details dashboard provides detailed information as to the operational status of the system(s).",
 "tags": [
  "synology",
  "dsm"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "NASDevices", "query": "1" },
   { "name": "interfacebits", "query": "8" },
   { "name": "JobName", "label": "Job Name", "query": { "query": "label_values(ssCpuUser, job)" } },
   {
    "name": "Device",
    "query": {
     "query": "query_result(ssCpuUser{job=~'$JobName'})"
    }
   },
   {
    "name": "Interface",
    "query": {
     "query": "label_values(ifName{job=~'$JobName',instance=~'$Device'},ifName)"
    }
   },
   {
    "name": "InterfacePhysical",
    "label": "Network Interface",
    "query": {
     "query": "label_values(ifName{job=~'$JobName',instance=~'$Device'},ifName)"
    }
   },
   {
    "name": "InterfaceVirtual",
    "label": "Virtual Interfaces",
    "query": {
     "query": "label_values(ifType_info{job=~'$JobName',instance=~'$Device'},ifName)"
    }
   },
   {
    "name": "DiskName",
    "label": "Disk",
    "query": {
     "query": "label_values(diskID{job=~'$JobName',instance=~'$Device'},diskID)"
    }
   },
   {
    "name": "DiskNameSSD",
    "label": "Cache",
    "query": {
     "query": "label_values(diskID{job=~'$JobName',instance=~'$Device'},diskID)"
    }
   },
   {
    "name": "raidName",
    "label": "Storage",
    "query": {
     "query": "label_values(raidName{job=~'$JobName',instance=~'$Device'},raidName)"
    }
   },
   {
    "name": "storageIODevice",
    "label": "Disk",
    "query": {
     "query": "label_values(storageIODevice{job=~'$JobName',instance=~'$Device'},storageIODevice)"
    }
   },
   {
    "name": "spaceIODevice",
    "label": "Volume Name",
    "query": {
     "query": "label_values(spaceIODevice{job=~'$JobName',instance=~'$Device'},spaceIODevice)"
    }
   },
   {
    "name": "hrStorageDescr",
    "label": "File System",
    "query": {
     "query": "label_values(hrStorageDescr{job=~'$JobName',instance=~'$Device'},hrStorageDescr)"
    }
   },
   {
    "name": "flashCacheDisk",
    "label": "Cache",
    "query": {
     "query": "label_values(flashCacheSSDDev{job=~'$JobName',instance=~'$Device'},flashCacheSSDDev)"
    }
   },
   {
    "name": "hrMemoryDescr",
    "label": "Memory",
    "query": {
     "query": "label_values(hrStorageDescr{job=~'$JobName',instance=~'$Device'},hrStorageDescr)"
    }
   },
   {
    "name": "SmartDev",
    "label": "S.M.A.R.T",
    "query": {
     "query": "label_values(diskSMARTInfoDevName{job=~'$JobName',instance=~'$Device'},diskSMARTInfoDevName)"
    }
   },
   {
    "name": "services",
    "query": {
     "query": "label_values(serviceName{job=~'$JobName',instance=~'$Device'},serviceName)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(count(up{instance=~\"$Device.*\"})/2)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 22, "x": 2, "y": 1 },
   "targets": [
    {
     "expr": "sysUpTime{job=~'$JobName',instance=~'$Device'}/100",
     "legendFormat": "uptime"
    },
    {
     "expr": "upgradeAvailable{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "temperature{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "cpuFanStatus{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "systemFanStatus{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "systemStatus{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "powerStatus{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "modelName{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "version{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "serialNumber{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "memTotalReal{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "diskIndex{job=~'$JobName',instance=~'$Device',diskID=~'$DiskName'}+1"
    }
   ]
  },
  {
   "title": "Volumes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 2, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(raidStatus{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'})",
     "legendFormat": "Total"
    },
    {
     "expr": "scalar(count((raidStatus{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}>=2 and raidStatus{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}<=10) or (raidStatus{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}>=13 and {job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}<=20)))",
     "legendFormat": "RAID Warning"
    },
    {
     "expr": "scalar(count((raidStatus{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}>=11 and raidStatus{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}<=12) or raidStatus{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}>21))",
     "legendFormat": "RAID Failure"
    }
   ]
  },
  {
   "title": "Drives",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 7, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(diskIndex{job=~'$JobName',instance=~'$Device',diskID=~'$DiskName'})",
     "legendFormat": "Total"
    },
    {
     "expr": "scalar(count(diskStatus{job=~'$JobName',instance=~'$Device',diskID=~'$DiskName'}>=2) and count(diskStatus{job=~'$JobName',instance=~'$Device',diskID=~'$DiskName'}<=3))",
     "legendFormat": "Not Used"
    },
    {
     "expr": "scalar(count(diskStatus{job=~'$JobName',instance=~'$Device',diskID=~'$DiskName'}>=4))",
     "legendFormat": "Failure"
    },
    {
     "expr": "count(diskSMARTAttrStatus{job=~'$JobName',instance=~'$Device'}==1)",
     "legendFormat": "SMART Checks"
    },
    {
     "expr": "scalar(count(diskSMARTAttrStatus{job=~'$JobName',instance=~'$Device',diskSMARTAttrStatus!=\"OK\"}==1))",
     "legendFormat": "SMART Failures"
    }
   ]
  },
  {
   "title": "Network Interfaces",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ifAdminStatus{job=~'$JobName',instance=~'$Device',ifName=~'$InterfacePhysical'}==1)",
     "legendFormat": "Enabled"
    },
    {
     "expr": "scalar(count(ifAdminStatus{job=~'$JobName',instance=~'$Device',ifName=~'$InterfacePhysical'}==2))",
     "legendFormat": "Disabled"
    },
    {
     "expr": "scalar((count(ifOperStatus{job=~'$JobName',instance=~'$Device',ifName=~'$InterfacePhysical'}==2)) - (count(ifAdminStatus{job=~'$JobName',instance=~'$Device',ifName=~'$InterfacePhysical'}==2)))",
     "legendFormat": "Down"
    }
   ]
  },
  { "title": "System Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ssCpuUser{job=~'$JobName',instance=~'$Device'} + ssCpuSystem{job=~'$JobName',instance=~'$Device'}",
     "legendFormat": "Used"
    },
    {
     "expr": "100-(ssCpuUser{job=~'$JobName',instance=~'$Device'} + ssCpuSystem{job=~'$JobName',instance=~'$Device'})",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(memTotalReal{job=~'$JobName',instance=~'$Device'} - (memAvailReal{job=~'$JobName',instance=~'$Device'} + memCached{job=~'$JobName',instance=~'$Device'} + memBuffer{job=~'$JobName',instance=~'$Device'})) / memTotalReal{job=~'$JobName',instance=~'$Device'}",
     "legendFormat": "Used"
    },
    {
     "expr": "1-((memTotalReal{job=~'$JobName',instance=~'$Device'} - (memAvailReal{job=~'$JobName',instance=~'$Device'} + memCached{job=~'$JobName',instance=~'$Device'} + memBuffer{job=~'$JobName',instance=~'$Device'})) / memTotalReal{job=~'$JobName',instance=~'$Device'})",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ssCpuSystem{job=~'$JobName',instance=~'$Device'}",
     "legendFormat": "System"
    },
    {
     "expr": "ssCpuUser{job=~'$JobName',instance=~'$Device'}",
     "legendFormat": "User"
    },
    {
     "expr": "ssCpuIdle{job=~'$JobName',instance=~'$Device'}",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Physical Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "memTotalReal{job=~'$JobName',instance=~'$Device'} ",
     "legendFormat": "Size"
    },
    {
     "expr": "memTotalReal{job=~'$JobName',instance=~'$Device'} - (memShared{job=~'$JobName',instance=~'$Device'} + memCached{job=~'$JobName',instance=~'$Device'} + memBuffer{job=~'$JobName',instance=~'$Device'} + memAvailReal{job=~'$JobName',instance=~'$Device'})",
     "legendFormat": "Reserved"
    },
    {
     "expr": "memBuffer{job=~'$JobName',instance=~'$Device'}",
     "legendFormat": "Buffer"
    },
    {
     "expr": "memCached{job=~'$JobName',instance=~'$Device'}",
     "legendFormat": "Cached"
    },
    {
     "expr": "memShared{job=~'$JobName',instance=~'$Device'}",
     "legendFormat": "Shared"
    },
    {
     "expr": "memAvailReal{job=~'$JobName',instance=~'$Device'}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "laLoadInt{job=~'$JobName',instance=~'$Device'}/100",
     "legendFormat": "{{laNames}}"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "memTotalReal{job=~'$JobName',instance=~'$Device'} + memTotalSwap{job=~'$JobName',instance=~'$Device'}",
     "legendFormat": "Size"
    },
    {
     "expr": "(memTotalReal{job=~'$JobName',instance=~'$Device'} + memTotalSwap{job=~'$JobName',instance=~'$Device'}) - memTotalFree{job=~'$JobName',instance=~'$Device'}",
     "legendFormat": "Used"
    },
    {
     "expr": "memTotalFree{job=~'$JobName',instance=~'$Device'}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hrSystemProcesses{job=~'$JobName',instance=~'$Device'}",
     "legendFormat": "Processes"
    }
   ]
  },
  {
   "title": "Users / Service",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "serviceUsers{job=~'$JobName',instance=~'$Device',serviceName=~'$services'}",
     "legendFormat": "{{serviceName}}"
    }
   ]
  },
  { "title": "System Internals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Network Interfaces",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "ifPhysAddress{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}"
    },
    {
     "expr": "ifAdminStatus{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}"
    },
    {
     "expr": "ifSpeed{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}"
    },
    {
     "expr": "ifOperStatus{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}"
    },
    {
     "expr": "ifMtu{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}"
    }
   ]
  },
  {
   "title": "Bond/Virtual Network Interface Information",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "ifPhysAddress{job=~'$JobName',instance=~'$Device',ifName=~'$InterfaceVirtual'}"
    },
    {
     "expr": "ifAdminStatus{job=~'$JobName',instance=~'$Device',ifName=~'$InterfaceVirtual'}"
    },
    {
     "expr": "ifSpeed{job=~'$JobName',instance=~'$Device',ifName=~'$InterfaceVirtual'}"
    },
    {
     "expr": "ifOperStatus{job=~'$JobName',instance=~'$Device',ifName=~'$InterfaceVirtual'}"
    },
    {
     "expr": "ifAlias{job=~'$JobName',instance=~'$Device',ifName=~'$InterfaceVirtual'}"
    },
    {
     "expr": "ifMtu{job=~'$JobName',instance=~'$Device',ifName=~'$InterfaceVirtual'}"
    }
   ]
  },
  {
   "title": "Hard Drives ",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "diskTemperature{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "diskType{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "diskStatus{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "diskModel{job=~'$JobName',instance=~'$Device'}"
    }
   ]
  },
  { "title": "Storage: $raidName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 }, "repeat": "raidName" },
  {
   "title": "RAID Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "raidStatus{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}"
    }
   ]
  },
  {
   "title": "Storage Usage - $raidName ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "raidTotalSize{job='$JobName',instance='$Device',raidName='$raidName'}",
     "legendFormat": "Size"
    },
    {
     "expr": "(raidTotalSize{job='$JobName',instance='$Device',raidName='$raidName'}-raidFreeSize{job='$JobName',instance='$Device',raidName='$raidName'})",
     "legendFormat": "Used"
    },
    {
     "expr": "raidFreeSize{job='$JobName',instance='$Device',raidName='$raidName'}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Storage Size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "raidTotalSize{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}"
    }
   ]
  },
  {
   "title": "% Used Space",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((raidTotalSize{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}-raidFreeSize{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'})/raidTotalSize{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'})*100",
     "legendFormat": "% Free"
    }
   ]
  },
  {
   "title": "File Systems: $hrStorageDescr ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 },
   "repeat": "hrStorageDescr",
   "collapsed": true,
   "panels": [
    {
     "title": "File System Size",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 194 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hrStorageSize{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrStorageDescr'} * hrStorageAllocationUnits{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrStorageDescr'}"
      }
     ]
    },
    {
     "title": "File System Usage: $hrStorageDescr ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 21, "x": 3, "y": 194 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "hrStorageSize{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrStorageDescr'} * hrStorageAllocationUnits{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrStorageDescr'}",
       "legendFormat": "Size"
      },
      {
       "expr": "hrStorageUsed{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrStorageDescr'} * hrStorageAllocationUnits{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrStorageDescr'}",
       "legendFormat": "Used"
      },
      {
       "expr": "(hrStorageSize{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrStorageDescr'} -  hrStorageUsed{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrStorageDescr'}) * hrStorageAllocationUnits{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrStorageDescr'}\n",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "% Used Space",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 196 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(hrStorageUsed{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrStorageDescr'} /hrStorageSize{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrStorageDescr'})*100",
       "legendFormat": "% Used"
      }
     ]
    }
   ]
  },
  {
   "title": "HDD/SSD: $storageIODevice",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 125 },
   "repeat": "storageIODevice",
   "collapsed": true,
   "panels": [
    {
     "title": "Bits Read/Write: $storageIODevice",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2378 },
     "targets": [
      {
       "expr": "rate(storageIONReadX{job=~'$JobName',instance=~'$Device',storageIODevice=~'$storageIODevice'}[$__rate_interval])",
       "legendFormat": "Read Bits"
      },
      {
       "expr": "rate(storageIONWrittenX{job=~'$JobName',instance=~'$Device',storageIODevice=~'$storageIODevice'}[$__rate_interval])",
       "legendFormat": "Write Bits"
      }
     ]
    },
    {
     "title": "I/O: $storageIODevice",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2378 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(storageIOLA{job=~'$JobName',instance=~'$Device',storageIODevice=~'$storageIODevice'}[$__rate_interval])",
       "legendFormat": "I/0"
      },
      {
       "expr": "rate(storageIOLA1{job=~'$JobName',instance=~'$Device',storageIODevice=~'$storageIODevice'}[$__rate_interval])",
       "legendFormat": "I/O 1 min avg"
      },
      {
       "expr": "rate(storageIOLA5{job=~'$JobName',instance=~'$Device',storageIODevice=~'$storageIODevice'}[$__rate_interval])",
       "legendFormat": "I/O 5 min avg"
      },
      {
       "expr": "rate(storageIOLA15{job=~'$JobName',instance=~'$Device',storageIODevice=~'$storageIODevice'}[$__rate_interval])",
       "legendFormat": "I/O 15  min avg"
      }
     ]
    },
    {
     "title": "Load: $storageIODevice",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2384 },
     "targets": [
      {
       "expr": "irate(storageIOReads{job=~'$JobName',instance=~'$Device',storageIODevice=~'$storageIODevice'}[$__rate_interval])",
       "legendFormat": "Read Load"
      },
      {
       "expr": "irate(storageIOWrites{job=~'$JobName',instance=~'$Device',storageIODevice=~'$storageIODevice'}[$__rate_interval])",
       "legendFormat": "Write Load"
      }
     ]
    }
   ]
  },
  {
   "title": "SSD Cache: $flashCacheDisk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 131 },
   "repeat": "flashCacheDisk",
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes Read/Write: $flashCacheDisk",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35636 },
     "targets": [
      {
       "expr": "rate(flashCacheDiskRead{job=~'$JobName',instance=~'$Device',flashCacheSSDDev=~'$flashCacheDisk'}[$__rate_interval])",
       "legendFormat": "Read Bytes"
      },
      {
       "expr": "rate(flashCacheDiskWrite{job=~'$JobName',instance=~'$Device',flashCacheSSDDev=~'$flashCacheDisk'}[$__rate_interval])",
       "legendFormat": "Written Bytes"
      }
     ]
    },
    {
     "title": "Read/Write Hits: $flashCacheDisk",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35636 },
     "targets": [
      {
       "expr": "rate(flashCacheReadHits{job=~'$JobName',instance=~'$Device',flashCacheSSDDev=~'$flashCacheDisk'}[$__rate_interval])",
       "legendFormat": "Read Hits"
      },
      {
       "expr": "rate(flashCacheWriteHits{job=~'$JobName',instance=~'$Device',flashCacheSSDDev=~'$flashCacheDisk'}[$__rate_interval])",
       "legendFormat": "Write Hits"
      }
     ]
    },
    {
     "title": "Read/Write Total: $flashCacheDisk",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35642 },
     "targets": [
      {
       "expr": "rate(flashCacheTotalRead{job=~'$JobName',instance=~'$Device',flashCacheSSDDev=~'$flashCacheDisk'}[$__rate_interval])",
       "legendFormat": "Total Read Hits"
      },
      {
       "expr": "rate(flashCacheTotalWrite{job=~'$JobName',instance=~'$Device',flashCacheSSDDev=~'$flashCacheDisk'}[$__rate_interval])",
       "legendFormat": "Total Write Hits"
      }
     ]
    },
    {
     "title": "Read/Write Hit Rate: $flashCacheDisk",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35642 },
     "targets": [
      {
       "expr": "rate(flashCacheReadHitRate{job=~'$JobName',instance=~'$Device',flashCacheSSDDev=~'$flashCacheDisk'}[$__rate_interval])",
       "legendFormat": "Read Hit Rate"
      },
      {
       "expr": "rate(flashCacheWriteHitRate{job=~'$JobName',instance=~'$Device',flashCacheSSDDev=~'$flashCacheDisk'}[$__rate_interval])",
       "legendFormat": "Write Hit Rate"
      }
     ]
    },
    {
     "title": "Read/Write Skips: $flashCacheDisk",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35648 },
     "targets": [
      {
       "expr": "rate(flashCacheReadSeqSkip{job=~'$JobName',instance=~'$Device',flashCacheSSDDev=~'$flashCacheDisk'}[$__rate_interval])",
       "legendFormat": "Read Skips"
      },
      {
       "expr": "rate(flashCacheWriteSeqSkip{job=~'$JobName',instance=~'$Device',flashCacheSSDDev=~'$flashCacheDisk'}[$__rate_interval])",
       "legendFormat": "Write Skips"
      }
     ]
    },
    {
     "title": "Write Misses: $flashCacheDisk",
     "type": "timeseries",
     "description": "The number of\ndata writes to SSD\nfor the first time",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35648 },
     "targets": [
      {
       "expr": "rate(flashCacheWriteMissSsd{job=~'$JobName',instance=~'$Device',flashCacheSSDDev=~'$flashCacheDisk'}[$__rate_interval])",
       "legendFormat": "Write Misses"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory: $hrMemoryDescr",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 132 },
   "repeat": "hrMemoryDescr",
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Size",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 210250 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hrStorageSize{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrMemoryDescr'} * hrStorageAllocationUnits{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrMemoryDescr'}"
      }
     ]
    },
    {
     "title": "Memory Usage: $hrMemoryDescr ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 21, "x": 3, "y": 210250 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "hrStorageSize{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrMemoryDescr'} * hrStorageAllocationUnits{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrMemoryDescr'}",
       "legendFormat": "Size"
      },
      {
       "expr": "hrStorageUsed{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrMemoryDescr'} * hrStorageAllocationUnits{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrMemoryDescr'}",
       "legendFormat": "Used"
      },
      {
       "expr": "(hrStorageSize{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrMemoryDescr'} -  hrStorageUsed{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrMemoryDescr'}) * hrStorageAllocationUnits{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrMemoryDescr'}\n",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "% Used Space",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 210252 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(hrStorageUsed{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrMemoryDescr'} /hrStorageSize{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrMemoryDescr'})*100",
       "legendFormat": "% Used"
      }
     ]
    }
   ]
  },
  {
   "title": "Networking: ($Interface)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 138 },
   "repeat": "Interface",
   "collapsed": true,
   "panels": [
    {
     "title": "Interfaces Details: $Interface",
     "type": "table",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1187772 },
     "targets": [
      {
       "expr": "ifPhysAddress{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}"
      },
      {
       "expr": "ifAdminStatus{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}"
      },
      {
       "expr": "ifConnectorPresent{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}"
      },
      {
       "expr": "ifSpeed{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}"
      },
      {
       "expr": "ifOperStatus{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}"
      },
      {
       "expr": "ifMtu{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}"
      }
     ]
    },
    {
     "title": "Traffic: $Interface",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1187775 },
     "targets": [
      {
       "expr": "rate(ifHCInOctets{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}[$__rate_interval])*$interfacebits",
       "legendFormat": "Traffic In"
      },
      {
       "expr": "rate(ifHCOutOctets{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}[$__rate_interval])*$interfacebits",
       "legendFormat": "Traffic Out"
      }
     ]
    },
    {
     "title": "Multicast & Broadcast: $Interface",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1187783 },
     "targets": [
      {
       "expr": "rate(ifHCInBroadcastPkts{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}[$__rate_interval])*$interfacebits",
       "legendFormat": "Broadcast In"
      },
      {
       "expr": "rate(ifHCOutBroadcastPkts{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}[$__rate_interval])*$interfacebits",
       "legendFormat": "Broadcast  Out"
      },
      {
       "expr": "rate(ifHCInMulticastPkts{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}[$__rate_interval])*$interfacebits",
       "legendFormat": "Multicast  In"
      },
      {
       "expr": "rate(ifHCOutMulticastPkts{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}[$__rate_interval])*$interfacebits",
       "legendFormat": "Multicast  Out"
      }
     ]
    },
    {
     "title": "Errors $Interface:",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1187783 },
     "targets": [
      {
       "expr": "rate(ifInDiscards{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}[$__rate_interval])",
       "legendFormat": "Discards In"
      },
      {
       "expr": "rate(ifInErrors{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}[$__rate_interval])",
       "legendFormat": "Errors In"
      },
      {
       "expr": "rate(ifOutDiscards{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}[$__rate_interval])",
       "legendFormat": "Discards Out"
      },
      {
       "expr": "rate(ifOutErrors{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}[$__rate_interval])",
       "legendFormat": "Errors Out"
      }
     ]
    }
   ]
  },
  {
   "title": "Volume: $spaceIODevice",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 141 },
   "repeat": "spaceIODevice",
   "collapsed": true,
   "panels": [
    {
     "title": "Volume Throughput - $spaceIODevice ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5314371 },
     "targets": [
      {
       "expr": "rate(spaceIONReadX{job=~'$JobName',instance=~'$Device',spaceIODevice=~'$spaceIODevice'}[$__rate_interval])",
       "legendFormat": "Read Bytes"
      },
      {
       "expr": "rate(spaceIONWrittenX{job=~'$JobName',instance=~'$Device',spaceIODevice=~'$spaceIODevice'}[$__rate_interval])",
       "legendFormat": "Written Bytes"
      }
     ]
    },
    {
     "title": "Volume IOPS - $spaceIODevice ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5314371 },
     "targets": [
      {
       "expr": "rate(spaceIOReads{job=~'$JobName',instance=~'$Device',spaceIODevice=~'$spaceIODevice'}[$__rate_interval])",
       "legendFormat": "Read Bytes"
      },
      {
       "expr": "rate(spaceIOWrites{job=~'$JobName',instance=~'$Device',spaceIODevice=~'$spaceIODevice'}[$__rate_interval])",
       "legendFormat": "Written Bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "SMART - ($SmartDev)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 146 },
   "repeat": "SmartDev",
   "collapsed": true,
   "panels": [
    {
     "title": "S.M.A.R.T ",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 32822195 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(diskSMARTInfoDevName{job=~'$JobName',instance=~'$Device',diskSMARTInfoDevName=~'$SmartDev'})",
       "legendFormat": "SMART Checks"
      }
     ]
    },
    {
     "title": "S.M.A.R.T: $SmartDev (Data is from the last time the Scheduled task was run)",
     "type": "table",
     "gridPos": { "h": 8, "w": 21, "x": 3, "y": 32822195 },
     "targets": [
      {
       "expr": "diskSMARTInfoDevName{job=~'$JobName',instance=~'$Device',diskSMARTInfoDevName='$SmartDev'}",
       "legendFormat": "SMARTInfo"
      },
      {
       "expr": "diskSMARTAttrName{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "AttrName"
      },
      {
       "expr": "diskSMARTAttrCurrent{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "AttrCurrent"
      },
      {
       "expr": "diskSMARTAttrThreshold{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "AttrThreshold"
      },
      {
       "expr": "diskSMARTAttrWorst{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "AttrWorst"
      },
      {
       "expr": "diskSMARTAttrStatus{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "AttrStatus"
      },
      {
       "expr": "diskSMARTAttrRaw{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "AttrRaw"
      }
     ]
    },
    {
     "title": "S.M.A.R.T: $SmartDev",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 32822199 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "diskSMARTInfoDevName{job=~'$JobName',instance=~'$Device',diskSMARTInfoDevName=~'$SmartDev'}",
       "legendFormat": "diskSMARTInfoDevName"
      },
      {
       "expr": "diskSMARTAttrStatus{job=~'$JobName',instance=~'$Device',diskSMARTAttrStatus!=\"OK\"}",
       "legendFormat": "diskSMARTAttrStatus"
      }
     ]
    }
   ]
  }
 ]
}