{
 "title": "Podman",
 "description": "This dashboard leverages Prometheus podman exporter as the data source and utilizes various visualization panels like time series and tables, providing critical insights into the operational metrics of Podman containers.",
 "tags": [ "podman" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(podman_container_info{instance=\"podman\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"podman\"}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(podman_container_state{instance=\"podman\"} == 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(podman_container_state{instance=\"podman\"} == 1)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(podman_container_state{instance=\"podman\"} == 2)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(podman_container_state{instance=\"podman\"} == 3)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(podman_container_state{instance=\"podman\"} == 4)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(podman_container_state{instance=\"podman\"} == 5)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(podman_container_state{instance=\"podman\"} == 6)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(podman_container_state{instance=\"podman\"} == 7)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(podman_container_state{instance=\"podman\"} == -1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Version",
   "type": "table",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "podman_system_api_version{instance=\"podman\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "podman_system_buildah_version{instance=\"podman\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "podman_system_conmon_version{instance=\"podman\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "podman_system_runtime_version{instance=\"podman\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Total CPU of containers",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(podman_container_cpu_seconds_total{instance=\"podman\"}[$__rate_interval])) / count(node_cpu_seconds_total{instance=\"node_exporter\",job=\"neem\",mode=\"idle\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (name) (podman_container_info{instance=\"podman\", name=~\"$container\"} * on(id) group_right (name) rate(podman_container_cpu_seconds_total[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Total memory of containers",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(podman_container_mem_usage_bytes{instance=\"podman\"}) / sum(node_memory_MemTotal_bytes{instance=\"node_exporter\",job=\"neem\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name) (\n    podman_container_info{instance=\"podman\", name=~\"$container\"}\n  * on (id) group_right (name)\n    (podman_container_mem_usage_bytes / 1024 / 1024)\n)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Recieved Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(name) (podman_container_info{instance=\"podman\", name=~\"$container\"} * on(id) group_right(name) rate(podman_container_net_input_total[1m]) / 1024)",
     "legendFormat": "{{name}} - Read"
    },
    {
     "expr": "sum(rate(podman_container_blkio_device_write_bytes_total{instance=\"podman\",name=~\"$container\"}[5m])) by (name)",
     "legendFormat": "{{name}} - Write"
    }
   ]
  },
  {
   "title": "Sent Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(name) (podman_container_info{instance=\"podman\", name=~\"$container\"} * on(id) group_right(name) rate(podman_container_net_output_total[1m]) / 1024)",
     "legendFormat": "{{name}} - Read"
    },
    {
     "expr": "sum(rate(podman_container_blkio_device_write_bytes_total{instance=\"podman\", name=~\"$container\"}[5m])) by (name)",
     "legendFormat": "{{name}} - Write"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Total Image Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(podman_image_size)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk Percentage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(podman_image_size{instance=\"podman\"}) / sum(node_filesystem_size_bytes{instance=\"node_exporter\",job=\"neem\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Volumes",
   "type": "table",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 30 },
   "targets": [
    {
     "expr": "podman_volume_info{instance=\"podman\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "podman_volume_created_seconds{instance=\"podman\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Image Info",
   "type": "table",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 36 },
   "targets": [
    {
     "expr": "podman_image_info{instance=\"podman\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "podman_image_created_seconds{instance=\"podman\"} * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "podman_image_size{instance=\"podman\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Overview",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "podman_container_info{instance=\"podman\", name=~\"$container\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(podman_container_info{instance=\"podman\", name=~\"$container\"} * on (id) group_right (name) (podman_container_state))",
     "legendFormat": "状态"
    },
    {
     "expr": "(podman_container_info{instance=\"podman\", name=~\"$container\"} * on (id) group_right (name) (podman_container_mem_usage_bytes))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(podman_container_info{instance=\"podman\", name=~\"$container\"} * on (id) group_right (name) (podman_container_exit_code))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(podman_container_info{instance=\"podman\", name=~\"$container\"} * on (id) group_right (name) (time() - podman_container_started_seconds))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(podman_container_info{instance=\"podman\", name=~\"$container\"} * on (id) group_right (name) (podman_container_pids))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(podman_container_info{instance=\"podman\", name=~\"$container\"} * on (id) group_right (name) (podman_container_mem_usage_bytes / (podman_container_mem_limit_bytes)))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(podman_container_info{instance=\"podman\", name=~\"$container\"} * on (id) group_right (name) (podman_container_health))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(podman_container_info{instance=\"podman\", name=~\"$container\"} * on(id) group_left(update_available) (label_replace(label_replace(wud_containers{instance=\"wud\"}, 'id', '$1', 'id', '(.{12}).*'), 'name', '$1', 'display_name', '(.*)')))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}